# Generated by Django 4.2.4 on 2023-10-03 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='created_At',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='created_At',
            new_name='created_at',
        ),
    ]
